### ISSUE TITLE
Can we use a custom dataset?

### ISSUE THREAD

**Issue by disturbed-mystic1** [cyj407/VQ-I2I#4]
I wanted to use this algorithm on my own custom dataset

**Comment by Badw0lf613** [comment]
@cyj407 The same need, could you give some advice

**Comment by cyj407** [comment]
You need to put your custom dataset (domain A and B) in a root folder and put the following 4 folders in this root folder:
1. trainA directory for domainA training images
2. trainB directory for domainB training images
3. testA directory for domainA testing images
4. testB directory for domainB testing images

, and modify the dataset path for your own root folder.
```
python unpair_train.py --root_dir <dataset_path>
```
