### ISSUE TITLE
Unpaired training with default config seems to require a lot of GPU memory

### ISSUE THREAD

**Issue by yesitsGao** [cyj407/VQ-I2I#6]
Hi,thanks for your amaing work. I try to train on first-stage unpair I2I task with default config. But it shows ：
RuntimeError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 23.70 GiB total capacity; 20.65 GiB already allocated; 62.00 MiB free; 20.92 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Actually，my machine have 23000Mib available. Does it truely cost such memoey or just i did something wrong? I am looking forward to your reply.

**Comment by liluying1996** [comment]
I have the same question

**Comment by cyj407** [comment]
We train this model for a single 3090Ti GPU with 32GB memory.

**Comment by cyj407** [comment]
Hi, we train our model on a single V100 gpu with 32G memory actually.
