### ISSUE TITLE
How long for training?

### ISSUE THREAD

**Issue by ShenZheng2000** [cyj407/VQ-I2I#7]
Hi, I would like to know how long it takes to train the network and how many GPUs you use for the experiments. Thanks!

**Comment by zhanjiahui** [comment]
same question👀

**Comment by cyj407** [comment]
Hi, we actually use a single 3090Ti GPU (32GB) for training, and spend a week to converge.

**Comment by cyj407** [comment]
Hi, we train it for a week on a single V100 GPU (32G).
